version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DATABASE_PORT}:3306
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}